package chain

import (
	"net/http"
	"time"

	"github.com/btcsuite/btcd/chaincfg"
)

// DASH uses the same block wire format as BTC (80-byte headers, same tx format).
// X11 PoW is not validated in the contract, so the BTC parser works.
// DASH uses P2SH instead of native SegWit on mainnet, but the mapping contract
// uses P2WSH internally so we keep the same address generator.
//
// Address version bytes must match dash-mapping-contract's init.go
// (dashMainNetParams / dashTestNetParams) — otherwise deposit addresses
// generated by the bot won't round-trip with addresses validated by the
// contract (different Bech32 HRP → different P2WSH encoding).

func dashMainNetParams() *chaincfg.Params {
	p := chaincfg.MainNetParams
	p.PubKeyHashAddrID = 0x4c // 'X' prefix
	p.ScriptHashAddrID = 0x10 // '7' prefix
	p.Bech32HRPSegwit = "dash"
	return &p
}

func dashTestNetParams() *chaincfg.Params {
	p := chaincfg.TestNet3Params
	p.PubKeyHashAddrID = 0x8c // 'y' prefix
	p.ScriptHashAddrID = 0x13 // '8'/'9' prefix
	p.Bech32HRPSegwit = "tdash"
	return &p
}

func NewDASHMainnet(httpClient *http.Client) *ChainConfig {
	params := dashMainNetParams()
	return &ChainConfig{
		Name:                 "dash",
		AssetSymbol:          "DASH",
		Client:               NewMempoolSpaceClient(httpClient, "https://insight.dash.org/insight-api"),
		Parser:               &BTCBlockParser{Params: params},
		AddressGen:           &BTCAddressGenerator{Params: params, BackupCSVBlocks: 17280},
		BlockInterval:        150 * time.Second, // 2.5 min blocks
		SleepInterval:        time.Minute,
		DropHeightDiff:       17280,
		HistoricalTxLookback: 4032, // ~7 days at 2.5 min
		ChainParams:          params,
		DefaultDbName:        "dash-mapping-bot",
	}
}

func NewDASHTestnet(httpClient *http.Client) *ChainConfig {
	params := dashTestNetParams()
	return &ChainConfig{
		Name:                 "dash",
		AssetSymbol:          "DASH",
		Client:               NewMempoolSpaceClient(httpClient, "https://insight.dash.org/insight-api-testnet"),
		Parser:               &BTCBlockParser{Params: params},
		AddressGen:           &BTCAddressGenerator{Params: params, BackupCSVBlocks: 2},
		BlockInterval:        150 * time.Second,
		SleepInterval:        10 * time.Second,
		DropHeightDiff:       17280,
		HistoricalTxLookback: 4032,
		ChainParams:          params,
		DefaultDbName:        "dash-mapping-bot-testnet",
	}
}

// NewDASHRegtest mirrors NewBTCRegtest. Uses unmodified RegressionNetParams
// to match the dash-mapping-contract's regtest branch (which also uses
// chaincfg.RegressionNetParams without a Dash overlay), so deposit addresses
// generated by the bot round-trip with what the contract validates.
func NewDASHRegtest(httpClient *http.Client) *ChainConfig {
	return &ChainConfig{
		Name:                 "dash",
		AssetSymbol:          "DASH",
		Client:               NewMempoolSpaceClient(httpClient, "http://localhost:3000/api"),
		Parser:               &BTCBlockParser{Params: &chaincfg.RegressionNetParams},
		AddressGen:           &BTCAddressGenerator{Params: &chaincfg.RegressionNetParams, BackupCSVBlocks: 2},
		BlockInterval:        time.Second,
		SleepInterval:        time.Second,
		DropHeightDiff:       100,
		HistoricalTxLookback: 100,
		ChainParams:          &chaincfg.RegressionNetParams,
		DefaultDbName:        "dash-mapping-bot-regtest",
	}
}
