package chain

import (
	"net/http"
	"time"

	"github.com/btcsuite/btcd/chaincfg"
)

// DOGE uses the same block wire format as BTC/LTC (Scrypt + AuxPoW, not
// validated in contract). 1-minute block time, P2WSH address format.
//
// Address version bytes must match doge-mapping-contract's init.go
// (dogeMainNetParams / dogeTestNetParams) — otherwise deposit addresses
// generated by the bot use Bitcoin's prefixes (1.../m...) instead of
// Dogecoin's (D.../n...) and won't round-trip with the contract.
//
// DOGE doesn't have native bech32, so Bech32HRPSegwit is left at the
// inherited Bitcoin value; the contract's P2WSH internal usage is
// independent of the chain's mainnet bech32 HRP.

// dogeMainNetParams returns Dogecoin mainnet parameters: P2PKH 0x1e
// ('D' prefix), P2SH 0x16 ('A'/'9' prefix). Mirrors the contract's
// overlay.
func dogeMainNetParams() *chaincfg.Params {
	params := chaincfg.MainNetParams
	params.PubKeyHashAddrID = 0x1e
	params.ScriptHashAddrID = 0x16
	return &params
}

// dogeTestNetParams returns Dogecoin testnet parameters: P2PKH 0x71
// ('n' prefix), P2SH 0xc4. Mirrors the contract's overlay.
func dogeTestNetParams() *chaincfg.Params {
	params := chaincfg.TestNet3Params
	params.PubKeyHashAddrID = 0x71
	params.ScriptHashAddrID = 0xc4
	return &params
}

func NewDOGEMainnet(httpClient *http.Client) *ChainConfig {
	params := dogeMainNetParams()
	return &ChainConfig{
		Name:                 "doge",
		AssetSymbol:          "DOGE",
		Client:               NewMempoolSpaceClient(httpClient, "https://blockchair.com/dogecoin/api"),
		Parser:               &BTCBlockParser{Params: params},
		AddressGen:           &BTCAddressGenerator{Params: params, BackupCSVBlocks: 43200},
		BlockInterval:        time.Minute, // 1 min blocks
		SleepInterval:        time.Minute,
		DropHeightDiff:       43200, // ~30 days at 1 min
		HistoricalTxLookback: 10080, // ~7 days at 1 min
		ChainParams:          params,
		DefaultDbName:        "doge-mapping-bot",
	}
}

func NewDOGETestnet(httpClient *http.Client) *ChainConfig {
	params := dogeTestNetParams()
	return &ChainConfig{
		Name:                 "doge",
		AssetSymbol:          "DOGE",
		Client:               NewMempoolSpaceClient(httpClient, "https://blockchair.com/dogecoin/testnet/api"),
		Parser:               &BTCBlockParser{Params: params},
		AddressGen:           &BTCAddressGenerator{Params: params, BackupCSVBlocks: 2},
		BlockInterval:        time.Minute,
		SleepInterval:        10 * time.Second,
		DropHeightDiff:       43200,
		HistoricalTxLookback: 10080,
		ChainParams:          params,
		DefaultDbName:        "doge-mapping-bot-testnet",
	}
}
