package chain

import (
	"net/http"
	"time"

	"github.com/btcsuite/btcd/chaincfg"
)

// LTC uses the same block wire format as BTC, but with different network params
// and a different block explorer API. Scrypt PoW is not validated in the contract
// so the BTC parser/address generator work as-is with LTC chaincfg params.
//
// Address version bytes must match ltc-mapping-contract's init.go
// (ltcMainNetParams / ltcTestNetParams) — otherwise deposit addresses
// generated by the bot won't round-trip with addresses validated by the
// contract.

// ltcMainNetParams returns Litecoin mainnet parameters: Bech32 HRP "ltc"
// + LTC's distinct address version bytes (P2PKH 0x30 = 'L' prefix,
// P2SH 0x32 = 'M' prefix). Mirrors the contract's overlay.
func ltcMainNetParams() *chaincfg.Params {
	params := chaincfg.MainNetParams
	params.PubKeyHashAddrID = 0x30 // 'L' prefix
	params.ScriptHashAddrID = 0x32 // 'M' prefix
	params.Bech32HRPSegwit = "ltc"
	return &params
}

// ltcTestNetParams returns Litecoin testnet parameters: Bech32 HRP "tltc"
// + LTC testnet's address version bytes (P2PKH 0x6f, P2SH 0xc4 — these
// happen to match Bitcoin testnet, but pin them explicitly to match the
// contract's overlay and to lock in the correct values regardless of
// future btcsuite changes).
func ltcTestNetParams() *chaincfg.Params {
	params := chaincfg.TestNet3Params
	params.PubKeyHashAddrID = 0x6f
	params.ScriptHashAddrID = 0xc4
	params.Bech32HRPSegwit = "tltc"
	return &params
}

func NewLTCMainnet(httpClient *http.Client) *ChainConfig {
	params := ltcMainNetParams()
	return &ChainConfig{
		Name:                 "ltc",
		AssetSymbol:          "LTC",
		Client:               NewMempoolSpaceClient(httpClient, "https://litecoinspace.org/api"),
		Parser:               &BTCBlockParser{Params: params},
		AddressGen:           &BTCAddressGenerator{Params: params, BackupCSVBlocks: 17280},
		BlockInterval:        150 * time.Second, // 2.5 min blocks
		SleepInterval:        time.Minute,
		DropHeightDiff:       17280, // ~30 days at 2.5 min
		HistoricalTxLookback: 4032,  // ~7 days at 2.5 min
		ChainParams:          params,
		DefaultDbName:        "ltc-mapping-bot",
	}
}

func NewLTCTestnet(httpClient *http.Client) *ChainConfig {
	params := ltcTestNetParams()
	return &ChainConfig{
		Name:                 "ltc",
		AssetSymbol:          "LTC",
		Client:               NewMempoolSpaceClient(httpClient, "https://litecoinspace.org/testnet/api"),
		Parser:               &BTCBlockParser{Params: params},
		AddressGen:           &BTCAddressGenerator{Params: params, BackupCSVBlocks: 2},
		BlockInterval:        150 * time.Second,
		SleepInterval:        10 * time.Second,
		DropHeightDiff:       17280,
		HistoricalTxLookback: 4032,
		ChainParams:          params,
		DefaultDbName:        "ltc-mapping-bot-testnet",
	}
}
