services:
  init:
    profiles: ["init"]
    build:
      dockerfile: Dockerfile
      context: .
    command: ./vsc-node --init
    environment:
      - MONGO_URL=mongodb://db:27017
    depends_on:
      - db
    networks:
      - go-vsc-node
    volumes:
      - ./data:/home/app/app/data
  app:
    profiles: ["default"]
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8094:8080"
      - "10724:10720"
      - "10724:10720/udp"
    environment:
      - MONGO_URL=mongodb://db:27017
    depends_on:
      - db
    networks:
      - go-vsc-node
    volumes:
      - ./data:/home/app/app/data
  db:
    image: mongo:8.0.17
    # restart: always
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - go-vsc-node
    volumes:
      - db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      retries: 5
      timeout: 5s
    deploy:
      resources:
        limits:
          memory: 1G
volumes:
  db: {}
networks:
  go-vsc-node:
    driver: bridge
