// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package contractinterface

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *SigningData) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "tx":
			z.Tx, err = dc.ReadBytes(z.Tx)
			if err != nil {
				err = msgp.WrapError(err, "Tx")
				return
			}
		case "uh":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "UnsignedSigHashes")
				return
			}
			if cap(z.UnsignedSigHashes) >= int(zb0002) {
				z.UnsignedSigHashes = (z.UnsignedSigHashes)[:zb0002]
			} else {
				z.UnsignedSigHashes = make([]UnsignedSigHash, zb0002)
			}
			for za0001 := range z.UnsignedSigHashes {
				var zb0003 uint32
				zb0003, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "UnsignedSigHashes", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "UnsignedSigHashes", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "i":
						z.UnsignedSigHashes[za0001].Index, err = dc.ReadUint32()
						if err != nil {
							err = msgp.WrapError(err, "UnsignedSigHashes", za0001, "Index")
							return
						}
					case "hs":
						z.UnsignedSigHashes[za0001].SigHash, err = dc.ReadBytes(z.UnsignedSigHashes[za0001].SigHash)
						if err != nil {
							err = msgp.WrapError(err, "UnsignedSigHashes", za0001, "SigHash")
							return
						}
					case "ws":
						z.UnsignedSigHashes[za0001].WitnessScript, err = dc.ReadBytes(z.UnsignedSigHashes[za0001].WitnessScript)
						if err != nil {
							err = msgp.WrapError(err, "UnsignedSigHashes", za0001, "WitnessScript")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "UnsignedSigHashes", za0001)
							return
						}
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SigningData) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "tx"
	err = en.Append(0x82, 0xa2, 0x74, 0x78)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Tx)
	if err != nil {
		err = msgp.WrapError(err, "Tx")
		return
	}
	// write "uh"
	err = en.Append(0xa2, 0x75, 0x68)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.UnsignedSigHashes)))
	if err != nil {
		err = msgp.WrapError(err, "UnsignedSigHashes")
		return
	}
	for za0001 := range z.UnsignedSigHashes {
		// map header, size 3
		// write "i"
		err = en.Append(0x83, 0xa1, 0x69)
		if err != nil {
			return
		}
		err = en.WriteUint32(z.UnsignedSigHashes[za0001].Index)
		if err != nil {
			err = msgp.WrapError(err, "UnsignedSigHashes", za0001, "Index")
			return
		}
		// write "hs"
		err = en.Append(0xa2, 0x68, 0x73)
		if err != nil {
			return
		}
		err = en.WriteBytes(z.UnsignedSigHashes[za0001].SigHash)
		if err != nil {
			err = msgp.WrapError(err, "UnsignedSigHashes", za0001, "SigHash")
			return
		}
		// write "ws"
		err = en.Append(0xa2, 0x77, 0x73)
		if err != nil {
			return
		}
		err = en.WriteBytes(z.UnsignedSigHashes[za0001].WitnessScript)
		if err != nil {
			err = msgp.WrapError(err, "UnsignedSigHashes", za0001, "WitnessScript")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SigningData) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "tx"
	o = append(o, 0x82, 0xa2, 0x74, 0x78)
	o = msgp.AppendBytes(o, z.Tx)
	// string "uh"
	o = append(o, 0xa2, 0x75, 0x68)
	o = msgp.AppendArrayHeader(o, uint32(len(z.UnsignedSigHashes)))
	for za0001 := range z.UnsignedSigHashes {
		// map header, size 3
		// string "i"
		o = append(o, 0x83, 0xa1, 0x69)
		o = msgp.AppendUint32(o, z.UnsignedSigHashes[za0001].Index)
		// string "hs"
		o = append(o, 0xa2, 0x68, 0x73)
		o = msgp.AppendBytes(o, z.UnsignedSigHashes[za0001].SigHash)
		// string "ws"
		o = append(o, 0xa2, 0x77, 0x73)
		o = msgp.AppendBytes(o, z.UnsignedSigHashes[za0001].WitnessScript)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SigningData) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "tx":
			z.Tx, bts, err = msgp.ReadBytesBytes(bts, z.Tx)
			if err != nil {
				err = msgp.WrapError(err, "Tx")
				return
			}
		case "uh":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UnsignedSigHashes")
				return
			}
			if cap(z.UnsignedSigHashes) >= int(zb0002) {
				z.UnsignedSigHashes = (z.UnsignedSigHashes)[:zb0002]
			} else {
				z.UnsignedSigHashes = make([]UnsignedSigHash, zb0002)
			}
			for za0001 := range z.UnsignedSigHashes {
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "UnsignedSigHashes", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "UnsignedSigHashes", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "i":
						z.UnsignedSigHashes[za0001].Index, bts, err = msgp.ReadUint32Bytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "UnsignedSigHashes", za0001, "Index")
							return
						}
					case "hs":
						z.UnsignedSigHashes[za0001].SigHash, bts, err = msgp.ReadBytesBytes(bts, z.UnsignedSigHashes[za0001].SigHash)
						if err != nil {
							err = msgp.WrapError(err, "UnsignedSigHashes", za0001, "SigHash")
							return
						}
					case "ws":
						z.UnsignedSigHashes[za0001].WitnessScript, bts, err = msgp.ReadBytesBytes(bts, z.UnsignedSigHashes[za0001].WitnessScript)
						if err != nil {
							err = msgp.WrapError(err, "UnsignedSigHashes", za0001, "WitnessScript")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "UnsignedSigHashes", za0001)
							return
						}
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SigningData) Msgsize() (s int) {
	s = 1 + 3 + msgp.BytesPrefixSize + len(z.Tx) + 3 + msgp.ArrayHeaderSize
	for za0001 := range z.UnsignedSigHashes {
		s += 1 + 2 + msgp.Uint32Size + 3 + msgp.BytesPrefixSize + len(z.UnsignedSigHashes[za0001].SigHash) + 3 + msgp.BytesPrefixSize + len(z.UnsignedSigHashes[za0001].WitnessScript)
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *UnsignedSigHash) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "i":
			z.Index, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "Index")
				return
			}
		case "hs":
			z.SigHash, err = dc.ReadBytes(z.SigHash)
			if err != nil {
				err = msgp.WrapError(err, "SigHash")
				return
			}
		case "ws":
			z.WitnessScript, err = dc.ReadBytes(z.WitnessScript)
			if err != nil {
				err = msgp.WrapError(err, "WitnessScript")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *UnsignedSigHash) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "i"
	err = en.Append(0x83, 0xa1, 0x69)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.Index)
	if err != nil {
		err = msgp.WrapError(err, "Index")
		return
	}
	// write "hs"
	err = en.Append(0xa2, 0x68, 0x73)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.SigHash)
	if err != nil {
		err = msgp.WrapError(err, "SigHash")
		return
	}
	// write "ws"
	err = en.Append(0xa2, 0x77, 0x73)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.WitnessScript)
	if err != nil {
		err = msgp.WrapError(err, "WitnessScript")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *UnsignedSigHash) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "i"
	o = append(o, 0x83, 0xa1, 0x69)
	o = msgp.AppendUint32(o, z.Index)
	// string "hs"
	o = append(o, 0xa2, 0x68, 0x73)
	o = msgp.AppendBytes(o, z.SigHash)
	// string "ws"
	o = append(o, 0xa2, 0x77, 0x73)
	o = msgp.AppendBytes(o, z.WitnessScript)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *UnsignedSigHash) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "i":
			z.Index, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Index")
				return
			}
		case "hs":
			z.SigHash, bts, err = msgp.ReadBytesBytes(bts, z.SigHash)
			if err != nil {
				err = msgp.WrapError(err, "SigHash")
				return
			}
		case "ws":
			z.WitnessScript, bts, err = msgp.ReadBytesBytes(bts, z.WitnessScript)
			if err != nil {
				err = msgp.WrapError(err, "WitnessScript")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *UnsignedSigHash) Msgsize() (s int) {
	s = 1 + 2 + msgp.Uint32Size + 3 + msgp.BytesPrefixSize + len(z.SigHash) + 3 + msgp.BytesPrefixSize + len(z.WitnessScript)
	return
}
