// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package sdk

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjson223cdf42DecodeVscNodeModulesWasmE2eGoWasmSdk(in *jlexer.Lexer, out *Env2) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "msg.required_auths":
			if in.IsNull() {
				in.Skip()
				out.Auths = nil
			} else {
				in.Delim('[')
				if out.Auths == nil {
					if !in.IsDelim(']') {
						out.Auths = make([]string, 0, 4)
					} else {
						out.Auths = []string{}
					}
				} else {
					out.Auths = (out.Auths)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Auths = append(out.Auths, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "msg.required_posting_auths":
			if in.IsNull() {
				in.Skip()
				out.PostingAuths = nil
			} else {
				in.Delim('[')
				if out.PostingAuths == nil {
					if !in.IsDelim(']') {
						out.PostingAuths = make([]string, 0, 4)
					} else {
						out.PostingAuths = []string{}
					}
				} else {
					out.PostingAuths = (out.PostingAuths)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					v2 = string(in.String())
					out.PostingAuths = append(out.PostingAuths, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "msg.sender":
			out.Sender = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson223cdf42EncodeVscNodeModulesWasmE2eGoWasmSdk(out *jwriter.Writer, in Env2) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"msg.required_auths\":"
		out.RawString(prefix[1:])
		if in.Auths == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Auths {
				if v3 > 0 {
					out.RawByte(',')
				}
				out.String(string(v4))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"msg.required_posting_auths\":"
		out.RawString(prefix)
		if in.PostingAuths == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.PostingAuths {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"msg.sender\":"
		out.RawString(prefix)
		out.String(string(in.Sender))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v Env2) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson223cdf42EncodeVscNodeModulesWasmE2eGoWasmSdk(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *Env2) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson223cdf42DecodeVscNodeModulesWasmE2eGoWasmSdk(l, v)
}
func tinyjson223cdf42DecodeVscNodeModulesWasmE2eGoWasmSdk1(in *jlexer.Lexer, out *Env) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "contract.id":
			out.ContractId = string(in.String())
		case "contract.owner":
			out.ContractOwner = string(in.String())
		case "tx.id":
			out.TxId = string(in.String())
		case "tx.index":
			out.Index = uint64(in.Uint64())
		case "tx.op_index":
			out.OpIndex = uint64(in.Uint64())
		case "block.id":
			out.BlockId = string(in.String())
		case "block.height":
			out.BlockHeight = uint64(in.Uint64())
		case "block.timestamp":
			out.Timestamp = string(in.String())
		case "sender":
			tinyjson223cdf42DecodeVscNodeModulesWasmE2eGoWasmSdk2(in, &out.Sender)
		case "msg.caller":
			out.Caller = Address(in.String())
		case "msg.payer":
			out.Payer = Address(in.String())
		case "intents.caller":
			if in.IsNull() {
				in.Skip()
				out.CallerIntents = nil
			} else {
				in.Delim('[')
				if out.CallerIntents == nil {
					if !in.IsDelim(']') {
						out.CallerIntents = make([]Intent, 0, 2)
					} else {
						out.CallerIntents = []Intent{}
					}
				} else {
					out.CallerIntents = (out.CallerIntents)[:0]
				}
				for !in.IsDelim(']') {
					var v7 Intent
					tinyjson223cdf42DecodeVscNodeModulesWasmE2eGoWasmSdk3(in, &v7)
					out.CallerIntents = append(out.CallerIntents, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "intents.sender":
			if in.IsNull() {
				in.Skip()
				out.SenderIntents = nil
			} else {
				in.Delim('[')
				if out.SenderIntents == nil {
					if !in.IsDelim(']') {
						out.SenderIntents = make([]Intent, 0, 2)
					} else {
						out.SenderIntents = []Intent{}
					}
				} else {
					out.SenderIntents = (out.SenderIntents)[:0]
				}
				for !in.IsDelim(']') {
					var v8 Intent
					tinyjson223cdf42DecodeVscNodeModulesWasmE2eGoWasmSdk3(in, &v8)
					out.SenderIntents = append(out.SenderIntents, v8)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson223cdf42EncodeVscNodeModulesWasmE2eGoWasmSdk1(out *jwriter.Writer, in Env) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"contract.id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ContractId))
	}
	{
		const prefix string = ",\"contract.owner\":"
		out.RawString(prefix)
		out.String(string(in.ContractOwner))
	}
	{
		const prefix string = ",\"tx.id\":"
		out.RawString(prefix)
		out.String(string(in.TxId))
	}
	{
		const prefix string = ",\"tx.index\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Index))
	}
	{
		const prefix string = ",\"tx.op_index\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.OpIndex))
	}
	{
		const prefix string = ",\"block.id\":"
		out.RawString(prefix)
		out.String(string(in.BlockId))
	}
	{
		const prefix string = ",\"block.height\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.BlockHeight))
	}
	{
		const prefix string = ",\"block.timestamp\":"
		out.RawString(prefix)
		out.String(string(in.Timestamp))
	}
	{
		const prefix string = ",\"sender\":"
		out.RawString(prefix)
		tinyjson223cdf42EncodeVscNodeModulesWasmE2eGoWasmSdk2(out, in.Sender)
	}
	{
		const prefix string = ",\"msg.caller\":"
		out.RawString(prefix)
		out.String(string(in.Caller))
	}
	{
		const prefix string = ",\"msg.payer\":"
		out.RawString(prefix)
		out.String(string(in.Payer))
	}
	{
		const prefix string = ",\"intents.caller\":"
		out.RawString(prefix)
		if in.CallerIntents == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.CallerIntents {
				if v9 > 0 {
					out.RawByte(',')
				}
				tinyjson223cdf42EncodeVscNodeModulesWasmE2eGoWasmSdk3(out, v10)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"intents.sender\":"
		out.RawString(prefix)
		if in.SenderIntents == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.SenderIntents {
				if v11 > 0 {
					out.RawByte(',')
				}
				tinyjson223cdf42EncodeVscNodeModulesWasmE2eGoWasmSdk3(out, v12)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v Env) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson223cdf42EncodeVscNodeModulesWasmE2eGoWasmSdk1(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *Env) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson223cdf42DecodeVscNodeModulesWasmE2eGoWasmSdk1(l, v)
}
func tinyjson223cdf42DecodeVscNodeModulesWasmE2eGoWasmSdk3(in *jlexer.Lexer, out *Intent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = string(in.String())
		case "args":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Args = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v13 string
					v13 = string(in.String())
					(out.Args)[key] = v13
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson223cdf42EncodeVscNodeModulesWasmE2eGoWasmSdk3(out *jwriter.Writer, in Intent) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"args\":"
		out.RawString(prefix)
		if in.Args == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v14First := true
			for v14Name, v14Value := range in.Args {
				if v14First {
					v14First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v14Name))
				out.RawByte(':')
				out.String(string(v14Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}
func tinyjson223cdf42DecodeVscNodeModulesWasmE2eGoWasmSdk2(in *jlexer.Lexer, out *Sender) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Address = Address(in.String())
		case "required_auths":
			if in.IsNull() {
				in.Skip()
				out.RequiredAuths = nil
			} else {
				in.Delim('[')
				if out.RequiredAuths == nil {
					if !in.IsDelim(']') {
						out.RequiredAuths = make([]Address, 0, 4)
					} else {
						out.RequiredAuths = []Address{}
					}
				} else {
					out.RequiredAuths = (out.RequiredAuths)[:0]
				}
				for !in.IsDelim(']') {
					var v15 Address
					v15 = Address(in.String())
					out.RequiredAuths = append(out.RequiredAuths, v15)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "required_posting_auths":
			if in.IsNull() {
				in.Skip()
				out.RequiredPostingAuths = nil
			} else {
				in.Delim('[')
				if out.RequiredPostingAuths == nil {
					if !in.IsDelim(']') {
						out.RequiredPostingAuths = make([]Address, 0, 4)
					} else {
						out.RequiredPostingAuths = []Address{}
					}
				} else {
					out.RequiredPostingAuths = (out.RequiredPostingAuths)[:0]
				}
				for !in.IsDelim(']') {
					var v16 Address
					v16 = Address(in.String())
					out.RequiredPostingAuths = append(out.RequiredPostingAuths, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson223cdf42EncodeVscNodeModulesWasmE2eGoWasmSdk2(out *jwriter.Writer, in Sender) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"required_auths\":"
		out.RawString(prefix)
		if in.RequiredAuths == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v17, v18 := range in.RequiredAuths {
				if v17 > 0 {
					out.RawByte(',')
				}
				out.String(string(v18))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"required_posting_auths\":"
		out.RawString(prefix)
		if in.RequiredPostingAuths == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v19, v20 := range in.RequiredPostingAuths {
				if v19 > 0 {
					out.RawByte(',')
				}
				out.String(string(v20))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func tinyjson223cdf42DecodeVscNodeModulesWasmE2eGoWasmSdk4(in *jlexer.Lexer, out *ContractCallOptions) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "intents":
			if in.IsNull() {
				in.Skip()
				out.Intents = nil
			} else {
				in.Delim('[')
				if out.Intents == nil {
					if !in.IsDelim(']') {
						out.Intents = make([]Intent, 0, 2)
					} else {
						out.Intents = []Intent{}
					}
				} else {
					out.Intents = (out.Intents)[:0]
				}
				for !in.IsDelim(']') {
					var v21 Intent
					tinyjson223cdf42DecodeVscNodeModulesWasmE2eGoWasmSdk3(in, &v21)
					out.Intents = append(out.Intents, v21)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson223cdf42EncodeVscNodeModulesWasmE2eGoWasmSdk4(out *jwriter.Writer, in ContractCallOptions) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Intents) != 0 {
		const prefix string = ",\"intents\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v22, v23 := range in.Intents {
				if v22 > 0 {
					out.RawByte(',')
				}
				tinyjson223cdf42EncodeVscNodeModulesWasmE2eGoWasmSdk3(out, v23)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v ContractCallOptions) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson223cdf42EncodeVscNodeModulesWasmE2eGoWasmSdk4(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *ContractCallOptions) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson223cdf42DecodeVscNodeModulesWasmE2eGoWasmSdk4(l, v)
}
