// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package params

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjson54f20b6DecodeBtcStubContractParams(in *jlexer.Lexer, out *InitParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "start_height":
			out.StartHeight = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson54f20b6EncodeBtcStubContractParams(out *jwriter.Writer, in InitParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"start_height\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.StartHeight))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v InitParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson54f20b6EncodeBtcStubContractParams(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *InitParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson54f20b6DecodeBtcStubContractParams(l, v)
}
func tinyjson54f20b6DecodeBtcStubContractParams1(in *jlexer.Lexer, out *AddBlocksParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "blocks":
			out.Blocks = string(in.String())
		case "latest_fee":
			out.LatestFee = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson54f20b6EncodeBtcStubContractParams1(out *jwriter.Writer, in AddBlocksParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"blocks\":"
		out.RawString(prefix[1:])
		out.String(string(in.Blocks))
	}
	{
		const prefix string = ",\"latest_fee\":"
		out.RawString(prefix)
		out.Int64(int64(in.LatestFee))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v AddBlocksParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson54f20b6EncodeBtcStubContractParams1(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *AddBlocksParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson54f20b6DecodeBtcStubContractParams1(l, v)
}
