// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package params

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjson54f20b6DecodeCallTssContractParams(in *jlexer.Lexer, out *Params) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "key_name":
			out.KeyName = string(in.String())
		case "msg_hex":
			out.MsgHex = string(in.String())
		case "epochs":
			out.Epochs = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson54f20b6EncodeCallTssContractParams(out *jwriter.Writer, in Params) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"key_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.KeyName))
	}
	if in.MsgHex != "" {
		const prefix string = ",\"msg_hex\":"
		out.RawString(prefix)
		out.String(string(in.MsgHex))
	}
	if in.Epochs != 0 {
		const prefix string = ",\"epochs\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Epochs))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v Params) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson54f20b6EncodeCallTssContractParams(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *Params) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson54f20b6DecodeCallTssContractParams(l, v)
}
