package gql

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/vektah/gqlparser/v2/ast"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Pentest finding F10: gqlgen's FixedComplexityLimit caps the
// total complexity score, but cheap leaf fields like __typename
// or localNodeInfo have a per-field complexity of 1, so an
// attacker can pack 1000+ aliases of those into a single request
// without ever tripping the complexity limit. Each alias is a
// separate execution.
//
// AliasLimit caps the total field-selection count per operation
// (top-level + nested) to bound that amplification independent
// of complexity. The default of DefaultAliasLimit covers
// every legitimate use we have observed against the production
// schema; raise via NewAliasLimit() if a future client needs
// genuinely larger aggregations.
//
// Pentest finding W-C1 (fragment depth DoS): two layered bugs.
//
// (a) The original countSelections walked fragment spreads without
// counting the spread itself and without memoization. A chain of
// N empty fragments yielded a count of 1 and bypassed the cap.
// Fixed by counting spreads and memoizing per fragment name.
//
// (b) gqlgen v0.17.81 graphql.collectFields has a doubling bug
// (executable_schema.go:81-89): when a fragment spread or inline
// fragment introduces a NEW field, the code creates the field by
// copying childField (which already has Selections populated) and
// THEN appends childField.Selections again, doubling the slice at
// every nesting level. A chain of N fragments whose leaf has a
// non-empty selection set (e.g. `types { name }`) therefore makes
// gqlgen allocate 2^N selection pointers at execute time:
//   - N=20 → 8 MB (slow, ~1s)
//   - N=30 → 8 GB (OOM)
//   - N=50 → unallocatable, process killed
// This exploded the testnet and techcoderx nodes against the
// payload `{ __schema { ...f1 } } fragment f1 on __Schema { ...f2 } ...`.
// The bug is downstream of every validator, so the only defense
// is to reject the request before execute. We do that by:
//
//   1. Capping fragment definitions per document at
//      DefaultMaxFragmentDefinitions. The doubling bug needs
//      depth ≥ 20 to be slow and ≥ 30 to OOM; capping the
//      *total* fragment count at 15 makes those depths
//      unreachable while remaining far above any legitimate
//      query (Apollo Sandbox introspection uses 3).
//   2. Capping the maximum fragment-spread / inline-fragment
//      *chain depth* at DefaultMaxFragmentDepth. Inline
//      fragments hit the same gqlgen doubling bug, so they
//      must be counted too; the depth walker treats both
//      identically.
//   3. Counting each spread as one selection so chained empty
//      fragments still contribute to the alias cap.
//   4. Memoizing per-fragment-name counts in countSelections
//      so the count itself is O(F+S) regardless of branching.
//   5. Defensive cycle guard in the memo even though
//      gqlparser's validator should reject cycles.

const (
	DefaultAliasLimit             = 100
	DefaultMaxFragmentDefinitions = 15
	DefaultMaxFragmentDepth       = 5
)

type aliasLimit struct {
	max int
}

// NewAliasLimit returns a gqlgen extension that rejects an
// operation when the total number of field selections (any
// nesting level, fragments resolved) exceeds max.
func NewAliasLimit(max int) graphql.HandlerExtension {
	return aliasLimit{max: max}
}

var _ interface {
	graphql.OperationContextMutator
	graphql.HandlerExtension
} = aliasLimit{}

func (aliasLimit) ExtensionName() string                     { return "AliasLimit" }
func (aliasLimit) Validate(_ graphql.ExecutableSchema) error { return nil }
func (a aliasLimit) MutateOperationContext(_ context.Context, opCtx *graphql.OperationContext) *gqlerror.Error {
	if n := len(opCtx.Doc.Fragments); n > DefaultMaxFragmentDefinitions {
		return gqlerror.Errorf(
			"operation has %d fragment definitions, exceeding the limit of %d",
			n, DefaultMaxFragmentDefinitions,
		)
	}
	op := opCtx.Doc.Operations.ForName(opCtx.OperationName)
	if op == nil {
		return nil
	}
	// Fragment chain depth — defends against the gqlgen
	// collectFields 2^N doubling bug (see file header comment (b)).
	// Walks named-fragment spreads AND inline fragments, since both
	// trigger the same allocator pattern. Runs BEFORE the
	// introspection exemption below: the OOM bug is shape-agnostic
	// and we can't trust an attacker-supplied operation just because
	// it has __schema at the top.
	depthMemo := make(map[string]int, len(opCtx.Doc.Fragments))
	if d := fragmentChainDepth(op.SelectionSet, opCtx.Doc.Fragments, depthMemo); d > DefaultMaxFragmentDepth {
		return gqlerror.Errorf(
			"operation fragment chain depth %d exceeds the limit of %d",
			d, DefaultMaxFragmentDepth,
		)
	}
	// Introspection queries (top-level is exclusively __schema and/or __type,
	// the GraphQL spec's schema-discovery roots) are generated by graphql-js
	// getIntrospectionQuery() and have a fixed, bounded shape. They
	// legitimately exceed the selection cap (~150 selections in the standard
	// query). Exempt them from the selection-count cap only — fragment
	// defs/depth above still apply. __typename is intentionally NOT in the
	// allow-list: alias amplification of __typename is exactly the F10 attack
	// vector. The top-level cardinality cap (introspectionTopLevelCap) bounds
	// the exemption tightly so a query like `{ __schema {...} __schema {...}
	// ... }` can't hide an amplification attack behind the introspection
	// allowance.
	if isIntrospectionOnly(op.SelectionSet) {
		return nil
	}
	memo := make(map[string]int, len(opCtx.Doc.Fragments))
	count := countSelections(op.SelectionSet, opCtx.Doc.Fragments, memo)
	if count > a.max {
		return gqlerror.Errorf(
			"operation has %d field selections, exceeding the alias / field-selection limit of %d",
			count, a.max,
		)
	}
	return nil
}

const introspectionTopLevelCap = 5

// isIntrospectionOnly reports whether every top-level selection in set is a
// field named __schema or __type (the spec-defined schema-discovery roots),
// and the total number of top-level selections is at most
// introspectionTopLevelCap. __typename is deliberately excluded — its alias
// amplification is the F10 attack vector. Any non-field selection at the top
// level, or any field that isn't __schema/__type, disqualifies the operation
// so a query mixing introspection with real fields still gets the alias cap.
func isIntrospectionOnly(set ast.SelectionSet) bool {
	if len(set) == 0 || len(set) > introspectionTopLevelCap {
		return false
	}
	for _, sel := range set {
		f, ok := sel.(*ast.Field)
		if !ok {
			return false
		}
		if f.Name != "__schema" && f.Name != "__type" {
			return false
		}
	}
	return true
}

// fragmentChainDepth returns the longest chain of fragment-spread
// or inline-fragment layers reachable from set. Each spread or
// inline fragment adds 1 to depth; ordinary fields reset to 0 for
// their sub-selection. The memo caches per-fragment-name results
// so the walk is O(F + S) even for branching fragment graphs.
//
// Cycle guard: each recursion seeds memo[name]=0 before descending
// so a cyclic spread (which gqlparser should reject) cannot loop
// here. The seed is overwritten with the real value before return.
func fragmentChainDepth(set ast.SelectionSet, fragments ast.FragmentDefinitionList, memo map[string]int) int {
	maxD := 0
	for _, sel := range set {
		var d int
		switch s := sel.(type) {
		case *ast.Field:
			// New field: chain depth resets for its sub-selection.
			d = fragmentChainDepth(s.SelectionSet, fragments, memo)
		case *ast.InlineFragment:
			d = 1 + fragmentChainDepth(s.SelectionSet, fragments, memo)
		case *ast.FragmentSpread:
			if c, ok := memo[s.Name]; ok {
				d = 1 + c
				break
			}
			def := fragments.ForName(s.Name)
			if def == nil {
				continue
			}
			memo[s.Name] = 0
			inner := fragmentChainDepth(def.SelectionSet, fragments, memo)
			memo[s.Name] = inner
			d = 1 + inner
		}
		if d > maxD {
			maxD = d
		}
	}
	return maxD
}

// countSelections walks an operation's selection tree and returns
// the total number of selections encountered. Fragment spreads
// expand to the fragment's selection set; inline fragments inline
// their own selection set. Each spread itself counts as one
// selection so a chain of empty fragments still contributes to
// the cap. memo caches the per-fragment-body count so a fragment
// referenced from many places is walked only once.
func countSelections(set ast.SelectionSet, fragments ast.FragmentDefinitionList, memo map[string]int) int {
	n := 0
	for _, sel := range set {
		switch s := sel.(type) {
		case *ast.Field:
			n++
			n += countSelections(s.SelectionSet, fragments, memo)
		case *ast.InlineFragment:
			n += countSelections(s.SelectionSet, fragments, memo)
		case *ast.FragmentSpread:
			n++
			if c, ok := memo[s.Name]; ok {
				n += c
				continue
			}
			def := fragments.ForName(s.Name)
			if def == nil {
				continue
			}
			// Defensive cycle guard: seed the memo with 0 before
			// recursing so a cyclic reference (which gqlparser
			// should already reject) cannot re-enter.
			memo[s.Name] = 0
			inner := countSelections(def.SelectionSet, fragments, memo)
			memo[s.Name] = inner
			n += inner
		}
	}
	return n
}
